### ISSUE TITLE
Rear View Radar Support for Magene L508

### ISSUE THREAD

**Issue by Elfsong** [zacharyedwardbull/pycycling#30] opened 2023-11-23 03:25 UTC
Hi @zacharyedwardbull and @tensorturtle,

I recently got a Magene L508 radar and am in the process of creating an iOS application to accompany it. However, I am encountering issues related to communication with the radar via the BLE protocol.

The crux of my challenge lies in not receiving any notifications from the radar. The preset service characteristic identified as '6a4e3203-667b-11e3-949a-0800200c9a66' used in "pycycling/rear_view_radar.py" doesn't seem to be compatible with the Magene L508.

**Could you provide some guidance on how to approach this issue? Do you perhaps know which service characteristic I should be using to rectify this communication issue with the radar?**

Thank you in advance for your help.

![Magene Radar](https://github.com/zacharyedwardbull/pycycling/assets/12135272/97326482-da0c-4b27-b9a2-7aaf2fa4d7bb)

**Comment by zacharyedwardbull** [comment] 2023-11-23 15:27
I'm closing this as a duplicate of #20.

**Closed as not planned by zacharyedwardbull** 2023-11-23 15:27 UTC
